export const CHAT_DETAILS_REQUEST = 'CHAT_DETAILS_REQUEST';
export const CHAT_DETAILS_SUCCESS = 'CHAT_DETAILS_SUCCESS';
export const CHAT_DETAILS_FAIL = 'CHAT_DETAILS_FAIL';

export const CHAT_DELETE_REQUEST = 'CHAT_DELETE_REQUEST';
export const CHAT_DELETE_SUCCESS = 'CHAT_DELETE_SUCCESS';
export const CHAT_DELETE_FAIL = 'CHAT_DELETE_FAIL';

export const CHAT_SEND_REQUEST = 'CHAT_SEND_REQUEST';
export const CHAT_SEND_SUCCESS = 'CHAT_SEND_SUCCESS';
export const CHAT_SEND_FAIL = 'CHAT_SEND_FAIL';

export const CHAT_SELECT_REQUEST = 'CHAT_SELECT_REQUEST';
export const CHAT_SELECT_SUCCESS = 'CHAT_SELECT_SUCCESS';
export const CHAT_SELECT_FAIL = 'CHAT_SELECT_FAIL';
